config/routes.rb
GuestByte::Application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }
  get "guests/create"
  get "responses/create"
  get "responses/delete"
  get "static_pages/home"
  get "static_pages/about"
  get "static_pages/contact"
  resources 'users', only: [:show] do
    resources :events
  end
  resources 'events', only: [:new, :index, :create, :show, :destroy]
  resources 'guests', only: [:create]
  resources 'prompts', only: [:create]
  resources 'responses', only: [:create]
  root 'static_pages#home'
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :title, presence: true,
            length: { maximum: 50 }
  has_many :prompts
  has_many :guests
  belongs_to :user
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :event
  validates :name, presence: true
  validates :affiliation, presence: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, 
                    :styles => { :medium => "300x300>", 
                                 :thumb => "100x100>" }, 
                    :default_url => "/images/:style/missing.png"
end

app/models/prompt.rb
class Prompt < ActiveRecord::Base
  belongs_to :event
  has_many :responses
  validates :content, presence: true

  def responses_by_newest
    self.responses.sort_by{|response| response.created_at}.reverse
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :prompt
  validates :content, presence: :true

  def age_in_minutes
    ((Time.now - created_at)/60).floor
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, only: :index

  def new
    @event = Event.new
  end

  def create
    @date = Date.new(params[:event]["date(1i)"].to_i,
                       params[:event]["date(2i)"].to_i,
                       params[:event]["date(3i)"].to_i)
    params['event']['date'] = @date
    @event = Event.new(event_params)
    if @event.save
      flash[:success] = 'Event successfully created!'
      redirect_to "/users/#{current_user.id}/events/#{@event.id}"
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])

    @prompt = Prompt.new(:event_id => @event.id)
  end

  def index
    @user = User.find(params[:user_id]) if params[:user_id]
    # binding.pry
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to user_events_path(current_user)
  end

private

  def event_params
    params.require(:event).permit(:host, :date, :title, :location, :start_time, :end_time, :description, :user_id)
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def create
    @guest = Guest.new(guest_params)
    if @guest.save
      flash[:success] = 'Thanks for signing in!'
      redirect_to "/events/#{params[:guest][:event_id]}/"
    else
      @event = Event.find(params[:guest][:event_id])
      # @prompt = Prompt.new
      render "/events/show.html.erb"
    end
  end

private
  def guest_params
    params.require(:guest).permit(:name, :affiliation, :email, :event_id, :avatar, :avatar_file_name)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def new
  end
end

app/controllers/prompts_controller.rb
class PromptsController < ApplicationController

  def create
    @prompt = Prompt.new(prompt_params)
    if @prompt.save
      redirect_to "/events/#{params[:prompt][:event_id]}/"
    else
      @event = Event.find(params[:prompt][:event_id])
      render "/events/show.html.erb"
    end
  end

  def destroy
  
  end

private
  
  def prompt_params
    params.require(:prompt).permit(:content, :event_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    user_events_path(resource)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def create
    @response = Response.new(response_params)
    @response.created_at = Time.now
    if @response.save
      redirect_to "/events/#{@response.prompt.event_id}/"
    else
      @event = Event.find(@response.prompt.event_id)
      @prompt = Prompt.new
      render "/events/show.html.erb"
    end
  end

  def delete
  end

private

  def response_params
    params.require(:response).permit(:content, :prompt_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  
  protected

  def after_sign_in_path_for(resource)
    user_events_path(resource)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @user = current_user
  end

  def contact

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/events/_guest_signin.html.erb
<div class="sign-in-form">
  <%= form_for @guest ||= Guest.new do |f| %>
 
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_field :name, :placeholder => "Name" %>
    <%= f.text_field :affiliation, :placeholder => "Affiliation" %>
    <%= f.text_field :email, :placeholder => "Email (optional)" %>
    <%= f.hidden_field :event_id, value: @event.id %>

    <%= f.submit "Add me!", class: "btn btn-sm btn-warning" %>
  <% end %>
</div>

app/views/events/_prompt.html.erb
<div class="col-6 col-sm-6 col-lg-6">
  <div class="prompt">
    <h3><%= prompt.content %></h3>
    
    <div class="responses">

      <% prompt.responses_by_newest.each do |response| %>
        <p><%= response.content %></p> 
        <p class="indent comment-time"><%= pluralize(response.age_in_minutes, 'minute') %> ago</p>
      <% end %>

    </div>
    <div class="comment-form">

      <%= form_for @response ||= prompt.responses.new do |f| %>

        <%= render 'shared/error_messages', object: f.object %>

        
        <%= f.hidden_field :prompt_id, value: prompt.id %>

        <div class="col-lg-offset-2 col-lg-10" id="comment-button">
          <%= f.text_area :content, id: "content#{@response.id}" %>
          <%= f.submit "Comment", class: "btn btn-sm btn-primary" %>
        </div>
      
      <% end %>
    </div>
  </div>
</div><!--/span-->

app/views/events/index.html.erb
<div class="row">
  <% if @user.events.empty? %>
    <%= link_to 'Get started by making some events!', new_event_path %> 
  <% else %>
    <div>
      <%= link_to 'New event', new_event_path %>
    </div>  
    <% @user.events.each do |event| %>
      <div class="col-6 col-sm-6 col-lg-4">
        <div class="prompt">
          <h2><%= event.title %></h2>
          <% if event.host %>
            <p>Hosted by: <%= event.host %></p>
          <% end %>
          <% if event.location %>
            <p>Location: <%= event.location %></p>
          <% end %>
          <% if event.date %>
            <p>Date: <%= event.date %></p>
          <% end %>
          <p><% if event.start_time %> 
            From <%= event.start_time.strftime('%l:%M %P') %> 
            <% end %>
            <% if event.end_time %>
            to <%= event.end_time.strftime('%l:%M %P') %>
          <% end %></p>
          <% if event.description %>
            <p class="home-description"><%= event.description ? event.description : "" %></p>
          <% end %>
          <div class="event-button">

            <p><%= button_to "View Event &raquo;".html_safe, event, method: :get, class: 'btn btn-default btn-primary'%></p>
              <% if @user == current_user %> 
                <p><%= button_to "Remove Event &raquo;".html_safe, event, method: :delete, class: 'btn btn-default btn-primary' %></p>
              <% end %>
          </div>
        </div>  
      </div><!--/span-->
    <% end %>
  <% end %>
</div><!--/row-->

app/views/events/new.html.erb
<%= form_for(@event, html: { :class => "form-horizontal", :role => "form" }) do |f| %>
  <%= render 'shared/error_messages', object: @event %>
  
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h1>New Event</h1>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title, :class => "col-lg-2 control-label" %>  
    <div class="col-lg-8">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :host, :class => "col-lg-2 control-label" %>  
    <div class="col-lg-8">
      <%= f.text_field :host, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date, :class => "col-lg-2 control-label" %>  
    <div class="col-lg-8">
      <%= date_select("event", "date", :start_year => 2013, :use_month_numbers => true) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => "col-lg-2 control-label" %>  
    <div class="col-lg-8">
      <%= f.text_field :location, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
  <%= f.label :start_time, :class => "col-lg-2 control-label" %>   
    <div class="col-lg-8">
      <%= time_select( :event, :start_time, prompt: { hour: 'Hour', minute: 'Minute', :ampm => true } ) %> 
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_time, :class => "col-lg-2 control-label" %>  
    <div class="col-lg-8">
      <%= time_select( :event, :end_time, prompt: { hour: 'Hour', minute: 'Minute', :ampm => true } ) %> 
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-lg-2 control-label" %>  
    <div class="col-lg-8">
      <%= f.text_field :description, :class => "form-control" %>
    </div>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <%= f.submit "Create event", class: "btn btn-large btn-primary" %>
    </div>
  </div>
  
<% end %>

app/views/events/show.html.erb
<div class="row row-offcanvas row-offcanvas-right">
  <div class="col-xs-12 col-sm-9">
    <div class="row">
      <div class="col-md-8">
        <h1><%= @event.title %></h1>
        <% unless @event.host.empty? %>
          <h3>Hosted by: <%= @event.host %></h3>
        <% end %>
        <% unless @event.location.empty? %>
          <h3>Location: <%= @event.location %></h3>
        <% end %>
        <% unless @event.date.nil? %>
          <h3>Date: <%= @event.date %></h3>
        <% end %>  
        <h3><% unless @event.start_time.nil? %> 
          From <%= @event.start_time.strftime('%l:%M %P') %> 
        <% end %>
        <% unless @event.end_time.nil? %>
          to <%= @event.end_time.strftime('%l:%M %P') %>
        <% end %></h3>         
      </div>  
      <div class="col-md-4">
        <% unless @event.description.empty? %>
          <h3><%= @event.description ? @event.description : "" %></h3>
        <% end %>
      </div>
    </div>
    
    <hr>

    <h4>Start the conversation!</h4>               
    <%= form_for @prompt ||= @event.prompts.new do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.text_field :content %>
      <%= f.hidden_field :event_id %> 
      <%= f.submit "Create prompt", class: "btn btn-large btn-warning" %>
    <% end %>

    <hr>

    <div class="row">
      <% if @event.prompts.empty? %>
        <p>Add a prompt to start the conversation!</p>
      <% end %>
      <% @event.prompts.each do |prompt| %>
        <%= render 'events/prompt', prompt: prompt %>
      <% end %>
    </div><!--/row-->
  </div>

  <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
    <div class="well sidebar-nav">
      <h2>Guest Book</h2>
      <hr>
      <h3>Sign your name</h3>
      <%= render 'events/guest_signin' %>
      <hr>
      <h3>Guests in attendance</h3>
      <% @event.guests.each do |guest| %>
        <p><%= guest.name %></p>
        <p class="indent">with <%= guest.affiliation %></p>
      <% end %>
    </div><!--/.well -->
  </div>
</div>

app/views/guests/create.html.erb
<h1>Guests#create</h1>
<p>Find me in app/views/guests/create.html.erb</p>

app/views/photos/new.html.erb
<div id="webcam">
<script type="text/javascript">
  webcam.set_swf_url('/webcam.swf');
  webcam.set_api_url('<%= upload_photos_path %>');
  webcam.set_quality(90);
  webcam.set_shutter_sound(true, '/shutter.mp3');
  $('webcam').append(webcam.get_html(640, 480));
</script>

<input type="button" value="Take picture" onclick="webcam.snap();" />
</div>

app/views/responses/create.html.erb
<h1>Responses#create</h1>
<p>Find me in app/views/responses/create.html.erb</p>

app/views/responses/delete.html.erb
<h1>Responses#delete</h1>
<p>Find me in app/views/responses/delete.html.erb</p>

app/views/static_pages/about.html.erb
<div class="jumbotron">
  <h1>Compelling title</h1>
  <p>franchise industrial grade advert plastic camera realism uplink motion tank-traps sentient drugs Shibuya monofilament. pistol neural military-grade systema meta- A.I. weathered neon 3D-printed narrative neon beef noodles cardboard. narrative nodality 8-bit wonton soup 8-bit sprawl bomb soul-delay sub-orbital cardboard uplink -ware savant. urban modem human wonton soup fetishism 3D-printed -space dome tank-traps rifle nodality human knife. disposable narrative city tiger-team claymore mine denim BASE jump digital realism shoes motion cartel bridge. rain plastic pistol face forwards woman systema market systemic military-grade RAF disposable assault ablative. DIY garage woman silent j-pop modem order-flow shanty town refrigerator network garage industrial grade numinous. post- beef noodles towards tiger-team rebar Chiba augmented reality sign rebar corrupted franchise marketing motion. receding sunglasses 3D-printed neural hotdog hotdog uplink -space shrine Kowloon motion -space convenience store.</p>
  <a href="https://github.com/abbysmalls/">Abby's Github</a>
  <a href="https://github.com/broguinn/">Braden's Github</a>
</div> 

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to GuestByte!</h1>
  <p>This is a real-time event management and interaction system. Invite guests to comment, create, and interact! When the party's over, review their most memorable blurbs, and follow up with your guests with our email helper.</p>
  <%= link_to 'Get started!', new_user_registration_path %>
</div>

app/views/static_pages/photo.html.erb
<%= headshot_default_config(Rails.application.config.session_options[:key], headshot_capture_path) %>

    <div class="camera">
      <%= headshot_camera(width = 190, height = 166.25) %>
    </div>
      
    <br/><br/>
   

    <%= headshot_snap_button('Shoot') %>

   